### ISSUE TITLE
Develop the components

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/open-profile#3]
We need to develop the components of this app.
No need to do API integration, we will just create the components from the wireframe. 

- [ ] Create Component for `Bio / Intro` Section
- [ ] Create Component for `Top Repo` Section
- [ ] Create Component for `Recent Activity` section
- [ ] Create Component for `Working On` section
- [ ] Create Component for `Testimonials` section
- [ ] Introduce icon library

We are using [shadcn UI](https://ui.shadcn.com/) and tailwind to do the designing.
